db = "/app/strfry-db"

dbParams {
  maxOpenFiles = 1024
}

relay {
  bind = "0.0.0.0"
  port = 7777
  nofiles = 65535

  writePolicy {
    plugin = "/opt/nostr-paper-relay-policy/policy.mjs"
    lookbackSeconds = 0
  }
}

events {
  maxEventSize = 131072
  rejectFutureSeconds = 900
}
